### ISSUE TITLE
Sync with Dropbox not working

### ISSUE THREAD

**Issue by yokuha** [masc4ii/WaoStats#6]
I've setup Dropbox access as per README, with access for the app to my complete dropbox. When I paste an updated Dropbox token  into the "sync dropbox" dialog, I only get the following error
![image](https://github.com/masc4ii/WaoStats/assets/124187637/8a51f6a6-e79a-4b1b-89dc-ed5abeb9f3ce)

Fit files are in `Apps/WahooFitness` as per default.

**Comment by masc4ii** [comment]
Thanks for the report. I need more info about your system, the used version and about what exactly you do (step by step).

I tried again with v1.2 official download and it works fine here, on macOS 10.13 (Intel) and macOS 11 (M1).

Maybe there are no new files, as you maybe already downloaded all files into the archive folder?
Has WaoStats write permission for the archive folder? Maybe enable in SystemPreferences.

**Comment by masc4ii** [comment]
Any news? Did you try again?
